<?php

namespace ShopAppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShopOrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopOrdersRepository extends EntityRepository
{
}
